### ISSUE TITLE
Missing DocumentPDF node

### ISSUE THREAD

**Issue by StevenXL** [docusign/recipe-010-webhook-python#3]
Hello,

I would like to extract the signed PDFs from a webhook. I am looking at [this recipe](https://www.docusign.com/developer-center/recipes/webhook-status).

Unfortunately, the XML sent via the webhook does not contain a `DocumentPDFs` node, and neither does the [example XML](https://www.docusign.com/supportdocs/api-docs-assets/DocuSign-REST-Recipes/010-webhook/example_completed_notification.xml) linked to in the docs. 

Am I missing something, or has the recipe gone out of date?

Thank you for any help.

**Comment by LarryKlugerDS** [comment]
Hi Steven,

I apologize for not seeing your issue until now. 

The documents are only included in the Connect notification messages if they are requested when the Connect subscription (at the account level) or the `eventNotification` (for per-envelope subscriptions) requests them.

As a best practice, it is recommended to not include the PDF documents in the notification messages since that causes the size of the notification messages to balloon. Instead, use the notification message to trigger your code to download the documents from DocuSign via the EnvelopeDocuments::get API method.
